server:
  port: 8000
  
# DATASOURCE
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.36.32:13306/api?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root

# MyBatis
mybatis:
  configLocation: classpath:/mybatis-config.xml